# Generated by Django 2.1.5 on 2019-01-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reivew',
            new_name='Review',
        ),
    ]
